apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dynatrace

resources:
  - ./namespace.yaml
# - ./operator-policy.yaml
# - ./operator.yaml


helmCharts:
  - name: dynatrace-operator
    namespace: dynatrace
    releaseName: dynatrace-operator
    repo: oci://public.ecr.aws/dynatrace/dynatrace-operator  