---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: dynatrace-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: dynatrace-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  source: certified-operators
  sourceNamespace: openshift-marketplace 
  name: dynatrace-operator