apiVersion: operators.operatorframework.io/v1alpha1
kind: OperatorGroup
metadata:
  name:  skupper-operator-group
  namespace: skupper-operator
spec:
  targetNamespaces: []
---
apiVersion: operators.operatorframework.io/v1alpha1
kind: Subscription
metadata:
  name: skupper-operator
  namespace: skupper-operator
spec:
  channel: stable
  startingCSV: skupper-operator.v1.8.5-rh-2
  name: skupper-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic