apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name:  skupper-operator-group
  namespace: skupper-operator
spec:
  targetNamespaces: []
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: skupper-operator
  namespace: skupper-operator
spec:
  channel: stable
  startingCSV: 18.5-rh-2
  name: 
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic