{{range .Values.rhel}}
{{- if eq .os "rhel9" -}}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ .hostname }}
  namespace: default
  osversion: rhel9
spec:
  dataVolumeTemplates:
    - metadata:
        name: {{ .hostname }}-rootdisk
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: '32212720254'
          storageClassName: lvms-vg1
  instancetype:
    name: u1.medium
  preference:
    name: rhel.9
  running: true
  template:
    metadata:
      labels:
        network.kubevirt.io/headlessService: headless
    spec:
      domain:
        devices:
          autoattachPodInterface: false
          disks:
            - disk:
                bus: scsi
              name: rootdisk
          interfaces:
            - bridge: {}
              model: virtio
              name: public-net-interface
      networks:
        - name: public-net-interface
          multus:
            networkName: default/vm-bridge
      subdomain: headless
      volumes:
        - dataVolume:
            name: {{ .hostname }}-rootdisk
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                expire: false
              password: redhat
              user: redhat
          name: cloudinitdisk
---
{{ end }}
{{ end }}