apiVersion: v1
kind: Namespace
metadata:
  name: openshift-lightspeed
  labels:
    kubernetes.io/metadata.name: openshift-lightspeed
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: openshift-gitops