apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: goldpinger
    repo: https://bloomberg.github.io/goldpinger
    version: 1.0.1
    releaseName: goldpinger
    namespace: goldpinger
    valuesInline:
      service:
        type: ClusterIP

resources:
  - namespace.yaml
