apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
 # - scc-rolebinding.yaml
  - scc-clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

configMapGenerator:
  - name: nginx-custom-page
    namespace: testdeploy
    files:
      - index.html