apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-anyuid
  namespace: testdeploy
roleRef:
  apiGroup: security.openshift.io
  kind: SecurityContextConstraints
  name: anyuid
subjects:
  - kind: ServiceAccount
    name: nginx-sa
    namespace: testdeploy
