apiVersion: v1
items:
- apiVersion: external-secrets.io/v1beta1
  kind: ClusterSecretStore
  metadata:
    name: aws-secretstore
  spec:
    provider:
      aws:
        auth:
          secretRef:
            accessKeyIDSecretRef:
              key: aws_access_key_id
              name: aws-credentials
            secretAccessKeySecretRef:
              key: aws_secret_access_key
              name: aws-credentials
        region: us-east-1
        service: SecretsManager
kind: List
metadata: {}