apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret2
  namespace: external-secrets-operator
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretstore
  target:
    name: my-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: test-value
      remoteRef:
        key: first-secret