apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 # - ../../groups/all
  #- ../../groups/prod
  - ../../components/kube-ops-view
  - ../../nmstate-configuration
# helmGlobals:
#   chartHome: ../../.helm-charts

# helmCharts:
# - name: argocd-app-of-app
#   valuesFile: values.yaml
# namespace: openshift-gitops


patches: [] 