apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: Network 1512 via OVS Bridge
  name: vlan-1512
  namespace: default
spec:
  config: |-
    {
        "cniVersion": "0.4.0",
        "name": "enp8s0",
        "type": "ovn-k8s-cni-overlay",
        "mtu": 1500,
        "netAttachDefName": "default/vm-bridge",
        "topology": "localnet"
    }
