apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: vm-brige
  name: vm-bridge
  namespace: default
spec:
  config: |-
    {
        "cniVersion": "0.4.0",
        "name": "enp8s0",
        "type": "ovn-k8s-cni-overlay",
        "mtu": 1500,
        "netAttachDefName": "default/vm-bridge",
        "topology": "localnet"
    }
