apiVersion: v1
items:
- apiVersion: lvm.topolvm.io/v1alpha1
  kind: LVMCluster
  metadata:
    name: my-lvmcluster
    namespace: openshift-storage
  spec:
    storage:
      deviceClasses:
      - default: true
        deviceSelector:
          paths:
          - /dev/sdb
        fstype: xfs
        name: vg1
        thinPoolConfig:
          chunkSizeCalculationPolicy: Static
          name: thin-pool-1
          overprovisionRatio: 10
          sizePercent: 90
kind: List
