apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-org.yaml
  - service.yaml
  - route.yaml

configMapGenerator:
  - name: nginx-custom-page
    files:
      - index.html