apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name:  pipelines-operator-group
  namespace: pipelines-operator
spec:
  targetNamespaces: []
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
  namespace: pipelines-operator
spec:
  channel: latest
  startingCSV: 18.0.1
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic