apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name:  pipelines-operator-group
  namespace: pipelines-operator
spec:
  targetNamespaces:
  -  pipelines-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
  namespace: pipelines-operator
spec:
  channel: latest
  version: 1.18.0
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic