apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: servicemesh-operator
spec:
  namespace: servicemesh-operator
  serviceAccount:
    name: servicemesh-operator
  source:
    sourceType: Catalog
    catalog:
      packageName: servicemeshoperator3
      channels:
        - stable
      version: "v3.0.2"