---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault-config-operator

resources:
  - ./namespace.yaml
#  - ./operator.yaml


helmCharts:
  - name: vault-config-operator
    namespace: vault-config-operator
    releaseName: vault-config-operator
    repo: https://github.com/hashicorp/vault-secrets-operator/tree/main/chart