---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: vault-config-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault-config-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  source: community-operators
  sourceNamespace: openshift-marketplace 
  name: vault-config-operator